server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security: trace

spring:
  application:
    name: authorization-server
  jpa:      
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default-schema: public
  datasource:
    url: jdbc:postgresql://localhost:5432/mytask
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
